"""add codigo_institucional to establecimiento

Revision ID: c1f007a27a31
Revises: ba09e45c0de4
Create Date: 2026-09-29 07:17:41.805877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f007a27a31'
down_revision: Union[str, Sequence[str], None] = 'ba09e45c0de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establecimiento', sa.Column('codigo_institucional', sa.String(length=50), nullable=False))
    op.create_unique_constraint('uq_establecimiento_codigo_institucional', 'establecimiento', ['codigo_institucional'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_establecimiento_codigo_institucional', 'establecimiento', type_='unique')
    op.drop_column('establecimiento', 'codigo_institucional')
    # ### end Alembic commands ###
