"""create cuenta_acceso table

Revision ID: ce2e5c2dc841
Revises: 3d1710ed97d0
Create Date: 2026-09-29 05:08:55.743204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2e5c2dc841'
down_revision: Union[str, Sequence[str], None] = '3d1710ed97d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta_acceso',
    sa.Column('id_cuenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=True),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=30), nullable=False),
    sa.Column('nombre_mostrado', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_cuenta'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('id_establecimiento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuenta_acceso')
    # ### end Alembic commands ###
